model = "willcb/Qwen3-0.6B"

[inference]
gpus = 1

[trainer]
gpus = 1
run_name = "gsm8k"

[trainer.args]
per_device_train_batch_size = 12
num_generations = 12
gradient_accumulation_steps = 8
max_steps = 100
eval_strategy = "steps"
eval_steps = 2
max_tokens = 1024
max_seq_len = 2048
